CertificateDsc: Add content parameter to ImportPFX and ImportCertificate resources
dsccommunity/CertificateDsc pull request #242
Opened 2020-11-23 22:11 UTC by 39Delta

#### Pull Request (PR) description
Updated the resources ImportPFX and ImportCertificate with the following:
* Added Base64Content parameter to specify the content of a PFX file that can be included in the configuration MOF.
* Added Base64Content parameter to specify the content of a certificate file that can be included in the configuration MOF.
* Updated unit and integration tests

#### This Pull Request (PR) fixes the following issues
- Issue #241 

#### Task list
- [x] Added an entry under the Unreleased section of the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in the resource folder.
- [x] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

2020-12-07 14:02 UTC, 39Delta commented
@PlagueHO, Updated to correct failing tests.

2020-12-15 05:42 UTC, 39Delta commented
Updated to send byte array directly to the certificate object during import and is ready for review.  Thanks!

2021-01-07 03:21 UTC, regedit32 reviewed
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/certificatedsc/242)* status: 1 of 14 files reviewed, 4 unresolved discussions (waiting on @39Delta and @PlagueHO)

*[a discussion](https://reviewable.io/reviews/dsccommunity/certificatedsc/242#-MQPr1NbA6qa7bm0hfJj:-MQPr1NbA6qa7bm0hfJk:b-3g0ab7) (no related file):*
Looks like Test-DscConfiguration integration tests are missing to cover the new changes?

---
___
*[source/DSCResources/DSC_CertificateImport/DSC_CertificateImport.psm1, line 105 at r3](https://reviewable.io/reviews/dsccommunity/certificatedsc/242#-MQPoJNMDlPRfCQ3Xkpb:-MQPoJNMDlPRfCQ3Xkpc:blokdo5) ([raw file](https://github.com/dsccommunity/certificatedsc/blob/ac421b611635530f4975fa4e7b69857de8b55e0b/source/DSCResources/DSC_CertificateImport/DSC_CertificateImport.psm1#L105)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
>     return @{
>         Thumbprint   = $Thumbprint
>         Path         = $Path
>         Location     = $Location
>         Store        = $Store
>         Ensure       = $Ensure
>         FriendlyName = $certificate.FriendlyName
>     }
> ```
</details>

Are we able to get the Base64 encoded content from the installed certificate, so `Content` can be included in the Get return?  Typically the Get return includes all the resource properties.
___
*[source/DSCResources/DSC_PfxImport/DSC_PfxImport.psm1, line 156 at r3](https://reviewable.io/reviews/dsccommunity/certificatedsc/242#-MQPpUbJ7VBVSjz8Ry4Z:-MQPpUbJ7VBVSjz8Ry4_:bi2jz0m) ([raw file](https://github.com/dsccommunity/certificatedsc/blob/ac421b611635530f4975fa4e7b69857de8b55e0b/source/DSCResources/DSC_PfxImport/DSC_PfxImport.psm1#L156)):*
<details><summary><i alt="summary">Quoted 9 lines of code…</i></summary>

> ```
>         Thumbprint   = $Thumbprint
>         Path         = $Path
>         Location     = $Location
>         Store        = $Store
>         Exportable   = $Exportable
>         Credential   = $Credential
>         Ensure       = $Ensure
>         FriendlyName = $certificate.FriendlyName
>     }
> ```
</details>

Are we able to get the Base64 encoded content from the installed certificate, so `Content` can be included in the Get return?  Typically the Get return includes all the resource properties.
___
*[tests/Integration/DSC_PfxImport.Integration.Tests.ps1, line 240 at r3](https://reviewable.io/reviews/dsccommunity/certificatedsc/242#-MQPqBc1E8Msd8clkCLN:-MQPqBc1E8Msd8clkCLO:bqb2jqz) ([raw file](https://github.com/dsccommunity/certificatedsc/blob/ac421b611635530f4975fa4e7b69857de8b55e0b/tests/Integration/DSC_PfxImport.Integration.Tests.ps1#L240)):*
> ```
>             It 'Should be able to call Get-DscConfiguration without throwing' {
>                 { Get-DscConfiguration -Verbose -ErrorAction Stop } | Should -Not -Throw
>             }
> ```
I'd recommend storing the output of Get-DscConfiguration and adding a test to assert the expected results.  This validates that each setting in the return hashtable is as expected.


<!-- Sent from Reviewable.io -->

2021-01-08 04:57 UTC, PlagueHO requested changes
Great stuff @39delta! I've made some comments. Will complete review of tests once you've had a chance to look at the comments. 

> Reviewed 2 of 14 files at r1, 5 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/certificatedsc/242#-:-MQVLZPm2qu9wU-l8kbY:b-v6xsiy)* status: 8 of 14 files reviewed, 17 unresolved discussions (waiting on @39Delta, @PlagueHO, and @regedit32)

___
*[CHANGELOG.md, line 12 at r3](https://reviewable.io/reviews/dsccommunity/certificatedsc/242#-MQVBjTzD4294WQ7SXrR:-MQVBjTzD4294WQ7SXrS:b-cvvniw) ([raw file](https://github.com/dsccommunity/certificatedsc/blob/ac421b611635530f4975fa4e7b69857de8b55e0b/CHANGELOG.md#L12)):*
> ```Markdown
> 
> - PfxImport:
>   - Added Base64Content parameter to specify the content of a PFX file that can be included in the configuration MOF.
> ```

Can you append the Issue to the end of this line in this format:
```... MOF  - Fixes [Issue #241](https://github.com/dsccommunity/CertificateDsc/issues/241).```
___
*[CHANGELOG.md, line 13 at r3](https://reviewable.io/reviews/dsccommunity/certificatedsc/242#-MQVBg290gbCy2m4404T:-MQVBg290gbCy2m4404U:buqthtb) ([raw file](https://github.com/dsccommunity/certificatedsc/blob/ac421b611635530f4975fa4e7b69857de8b55e0b/CHANGELOG.md#L13)):*
> ```Markdown
> - PfxImport:
>   - Added Base64Content parameter to specify the content of a PFX file that can be included in the configuration MOF.
> ```

Can you remove the blank line between these entries?
___
*[CHANGELOG.md, line 15 at r3](https://reviewable.io/reviews/dsccommunity/certificatedsc/242#-MQVBwo6B-ISVR7LM1v3:-MQVBwo6B-ISVR7LM1v4:b-cvvniw) ([raw file](https://github.com/dsccommunity/certificatedsc/blob/ac421b611635530f4975fa4e7b69857de8b55e0b/CHANGELOG.md#L15)):*
> ```Markdown
> 
> - CertificateImport:
>   - Added Base64Content parameter to specify the content of a certificate file that can be included in the configuration MOF.
> ```

Can you append the Issue to the end of this line in this format:
```... MOF  - Fixes [Issue #241](https://github.com/dsccommunity/CertificateDsc/issues/241).```
___
*[CHANGELOG.md, line 20 at r3](https://reviewable.io/reviews/dsccommunity/certificatedsc/242#-MQVByvZ6Jm7p7wNtWpw:-MQVByvZ6Jm7p7wNtWpx:b-iqzjmf) ([raw file](https://github.com/dsccommunity/certificatedsc/blob/ac421b611635530f4975fa4e7b69857de8b55e0b/CHANGELOG.md#L20)):*
> ```Markdown
> 
> - Renamed `master` branch to `main` - Fixes [Issue #237](https://github.com/dsccommunity/CertificateDsc/issues/237).
> ```

Can this blank line be removed?
___
*[source/DSCResources/DSC_CertificateImport/DSC_CertificateImport.psm1, line 55 at r3](https://reviewable.io/reviews/dsccommunity/certificatedsc/242#-MQVCnpV--0lUZbfUUvW:-MQVCnpV--0lUZbfUUvX:b-ci4on9) ([raw file](https://github.com/dsccommunity/certificatedsc/blob/ac421b611635530f4975fa4e7b69857de8b55e0b/source/DSCResources/DSC_CertificateImport/DSC_CertificateImport.psm1#L55)):*
> ```PowerShell
>         $Thumbprint,
> 
>         [Parameter(Mandatory = $true)]
> ```

One thing I'm thinking here is that we should make the `$Path` parameter non-mandatory. It doesn't make sense to pass both the `$Path` and the `$Content` parameters.

What we'd normally do is dd a function that validates the parameter combination is valid using a function `Assert-ResourceProperty` - e.g. https://github.com/dsccommunity/NetworkingDsc/blob/ea0d30629c1d44d7a13685977783fdbf3159e4b4/source/DSCResources/DSC_WinsServerAddress/DSC_WinsServerAddress.psm1#L35

This would also apply to the PFXImport.

Sidenote: This parameter and Content, Ensure and FriendlyName shouldn't actually be enabled in `Get-TargetResource`. I've added a separate issue to resolve this in future: https://github.com/dsccommunity/CertificateDsc/issues/244 - don't worry about it for this PR - just something we need to fix up in future to be compliant with standards.
___
*[source/DSCResources/DSC_CertificateImport/DSC_CertificateImport.psm1, line 105 at r3](https://reviewable.io/reviews/dsccommunity/certificatedsc/242#-MQPoJNMDlPRfCQ3Xkpb:-MQVC5oU9nD6iWWrAy3E:bb6mt9b) ([raw file](https://github.com/dsccommunity/certificatedsc/blob/ac421b611635530f4975fa4e7b69857de8b55e0b/source/DSCResources/DSC_CertificateImport/DSC_CertificateImport.psm1#L105)):*
<details><summary><i>Previously, regedit32 (Reggie Gibson) wrote…</i></summary><blockquote>

> ```
>     return @{
>         Thumbprint   = $Thumbprint
>         Path         = $Path
>         Location     = $Location
>         Store        = $Store
>         Ensure       = $Ensure
>         FriendlyName = $certificate.FriendlyName
>     }
> ```
Are we able to get the Base64 encoded content from the installed certificate, so `Content` can be included in the Get return?  Typically the Get return includes all the resource properties.
</blockquote></details>

:+1:
___
*[source/DSCResources/DSC_CertificateImport/DSC_CertificateImport.psm1, line 308 at r3](https://reviewable.io/reviews/dsccommunity/certificatedsc/242#-MQVFv6YEHnRDPGDW-LN:-MQVFv6YEHnRDPGDW-LO:b96dl96) ([raw file](https://github.com/dsccommunity/certificatedsc/blob/ac421b611635530f4975fa4e7b69857de8b55e0b/source/DSCResources/DSC_CertificateImport/DSC_CertificateImport.psm1#L308)):*
> ```PowerShell
>             {
>                 # Check that the certificate file exists before trying to import
>                 if (-not (Test-Path -Path $Path))
> ```

FYI: If we used the `Assert-ResourceProperty` pattern then we could actually shift this check into that function. Not required, just a thought.
___
*[source/DSCResources/DSC_CertificateImport/DSC_CertificateImport.schema.mof, line 5 at r3](https://reviewable.io/reviews/dsccommunity/certificatedsc/242#-MQVGjJa2Y43zGuOtm9T:-MQVGjJa2Y43zGuOtm9U:bgxbp62) ([raw file](https://github.com/dsccommunity/certificatedsc/blob/ac421b611635530f4975fa4e7b69857de8b55e0b/source/DSCResources/DSC_CertificateImport/DSC_CertificateImport.schema.mof#L5)):*
> ```
> {
>     [Key,Description("The thumbprint (unique identifier) of the certificate you're importing.")] string Thumbprint;
>     [Required,Description("The path to the CER file you want to import.")] string Path;
> ```

See previous comment about changing this to a `Write` parameter. I'm thinking that if we do that we should also change the description to indicate that this parameter should not be set if `Content` parameter is set - and same to the Content parameter.
___
*[source/DSCResources/DSC_PfxImport/DSC_PfxImport.psm1, line 1 at r3](https://reviewable.io/reviews/dsccommunity/certificatedsc/242#-MQVHLQxCOYU-x1oOVIV:-MQVHLQxCOYU-x1oOVIW:b-dbnimi) ([raw file](https://github.com/dsccommunity/certificatedsc/blob/ac421b611635530f4975fa4e7b69857de8b55e0b/source/DSCResources/DSC_PfxImport/DSC_PfxImport.psm1#L1)):*
> ```PowerShell
> #Requires -Version 4.0
> ```

Same comments for this file as the CertificateImport PSM1.
___
*[source/DSCResources/DSC_PfxImport/DSC_PfxImport.psm1, line 156 at r3](https://reviewable.io/reviews/dsccommunity/certificatedsc/242#-MQPpUbJ7VBVSjz8Ry4Z:-MQVCMPM5YJVkkOFp74g:bb6mt9b) ([raw file](https://github.com/dsccommunity/certificatedsc/blob/ac421b611635530f4975fa4e7b69857de8b55e0b/source/DSCResources/DSC_PfxImport/DSC_PfxImport.psm1#L156)):*
<details><summary><i>Previously, regedit32 (Reggie Gibson) wrote…</i></summary><blockquote>

> ```
>         Thumbprint   = $Thumbprint
>         Path         = $Path
>         Location     = $Location
>         Store        = $Store
>         Exportable   = $Exportable
>         Credential   = $Credential
>         Ensure       = $Ensure
>         FriendlyName = $certificate.FriendlyName
>     }
> ```
Are we able to get the Base64 encoded content from the installed certificate, so `Content` can be included in the Get return?  Typically the Get return includes all the resource properties.
</blockquote></details>

:+1:
___
*[source/DSCResources/DSC_PfxImport/DSC_PfxImport.psm1, line 386 at r3](https://reviewable.io/reviews/dsccommunity/certificatedsc/242#-MQVIYbj7zL10 [...]

2021-01-15 07:09 UTC, 39Delta reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/certificatedsc/242)* status: 1 of 16 files reviewed, 17 unresolved discussions (waiting on @39Delta, @PlagueHO, and @regedit32)

*[a discussion](https://reviewable.io/reviews/dsccommunity/certificatedsc/242#-MQPr1NbA6qa7bm0hfJj:-MR3kj3ACHPejrdZPIa6:bfnljoa) (no related file):*
<details><summary><i>Previously, regedit32 (Reggie Gibson) wrote…</i></summary><blockquote>

Looks like Test-DscConfiguration integration tests are missing to cover the new changes?
</blockquote></details>

There were no changes to the Test-DscConfiguration logic as it only tests for the presence or absence of a certificate in the cert store by thumbprint.  The new parameters are ignored by this function.

---
___
*[CHANGELOG.md, line 12 at r3](https://reviewable.io/reviews/dsccommunity/certificatedsc/242#-MQVBjTzD4294WQ7SXrR:-MR3lFkXDIH04mdnI_ay:b-896fix) ([raw file](https://github.com/dsccommunity/certificatedsc/blob/ac421b611635530f4975fa4e7b69857de8b55e0b/CHANGELOG.md#L12)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you append the Issue to the end of this line in this format:
```... MOF  - Fixes [Issue #241](https://github.com/dsccommunity/CertificateDsc/issues/241).```
</blockquote></details>

Done.
___
*[CHANGELOG.md, line 13 at r3](https://reviewable.io/reviews/dsccommunity/certificatedsc/242#-MQVBg290gbCy2m4404T:-MR3lHWz52rXbiH6olT9:b-896fix) ([raw file](https://github.com/dsccommunity/certificatedsc/blob/ac421b611635530f4975fa4e7b69857de8b55e0b/CHANGELOG.md#L13)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you remove the blank line between these entries?
</blockquote></details>

Done.
___
*[CHANGELOG.md, line 15 at r3](https://reviewable.io/reviews/dsccommunity/certificatedsc/242#-MQVBwo6B-ISVR7LM1v3:-MR3lIir6btxnSf0CIuF:b-896fix) ([raw file](https://github.com/dsccommunity/certificatedsc/blob/ac421b611635530f4975fa4e7b69857de8b55e0b/CHANGELOG.md#L15)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you append the Issue to the end of this line in this format:
```... MOF  - Fixes [Issue #241](https://github.com/dsccommunity/CertificateDsc/issues/241).```
</blockquote></details>

Done.
___
*[CHANGELOG.md, line 20 at r3](https://reviewable.io/reviews/dsccommunity/certificatedsc/242#-MQVByvZ6Jm7p7wNtWpw:-MR3lKBn1LwKVkPPcRUB:b-896fix) ([raw file](https://github.com/dsccommunity/certificatedsc/blob/ac421b611635530f4975fa4e7b69857de8b55e0b/CHANGELOG.md#L20)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can this blank line be removed?
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_CertificateImport/DSC_CertificateImport.psm1, line 55 at r3](https://reviewable.io/reviews/dsccommunity/certificatedsc/242#-MQVCnpV--0lUZbfUUvW:-MR3lQ2r54i1qMQk9LIe:b-896fix) ([raw file](https://github.com/dsccommunity/certificatedsc/blob/ac421b611635530f4975fa4e7b69857de8b55e0b/source/DSCResources/DSC_CertificateImport/DSC_CertificateImport.psm1#L55)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

One thing I'm thinking here is that we should make the `$Path` parameter non-mandatory. It doesn't make sense to pass both the `$Path` and the `$Content` parameters.

What we'd normally do is dd a function that validates the parameter combination is valid using a function `Assert-ResourceProperty` - e.g. https://github.com/dsccommunity/NetworkingDsc/blob/ea0d30629c1d44d7a13685977783fdbf3159e4b4/source/DSCResources/DSC_WinsServerAddress/DSC_WinsServerAddress.psm1#L35

This would also apply to the PFXImport.

Sidenote: This parameter and Content, Ensure and FriendlyName shouldn't actually be enabled in `Get-TargetResource`. I've added a separate issue to resolve this in future: https://github.com/dsccommunity/CertificateDsc/issues/244 - don't worry about it for this PR - just something we need to fix up in future to be compliant with standards.
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_CertificateImport/DSC_CertificateImport.psm1, line 105 at r3](https://reviewable.io/reviews/dsccommunity/certificatedsc/242#-MQPoJNMDlPRfCQ3Xkpb:-MR3lTL37KPZZb8I1kui:boa5a50) ([raw file](https://github.com/dsccommunity/certificatedsc/blob/ac421b611635530f4975fa4e7b69857de8b55e0b/source/DSCResources/DSC_CertificateImport/DSC_CertificateImport.psm1#L105)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

:+1:
</blockquote></details>

We can for the public key but keep in mind the encoded value will be different if the user has configured a new friendly name through the parameter and should not be relied on for comparison.  The thumbprint is best ID to compare.  If we think their is value in exposing the currently installed cert value then I can add.  Thoughts?
___
*[source/DSCResources/DSC_CertificateImport/DSC_CertificateImport.psm1, line 308 at r3](https://reviewable.io/reviews/dsccommunity/certificatedsc/242#-MQVFv6YEHnRDPGDW-LN:-MR3mnsM3yOQl1tZ-U74:b-9mv6ep) ([raw file](https://github.com/dsccommunity/certificatedsc/blob/ac421b611635530f4975fa4e7b69857de8b55e0b/source/DSCResources/DSC_CertificateImport/DSC_CertificateImport.psm1#L308)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

FYI: If we used the `Assert-ResourceProperty` pattern then we could actually shift this check into that function. Not required, just a thought.
</blockquote></details>

I left it here because the logic path is not always hit when set runs.  If the cert is installed but the friendly name is incorrect then the path does not need to be tested for the cert to be updated.
___
*[source/DSCResources/DSC_CertificateImport/DSC_CertificateImport.schema.mof, line 5 at r3](https://reviewable.io/reviews/dsccommunity/certificatedsc/242#-MQVGjJa2Y43zGuOtm9T:-MR3na9q1hTZXOb2EyZW:b-896fix) ([raw file](https://github.com/dsccommunity/certificatedsc/blob/ac421b611635530f4975fa4e7b69857de8b55e0b/source/DSCResources/DSC_CertificateImport/DSC_CertificateImport.schema.mof#L5)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

See previous comment about changing this to a `Write` parameter. I'm thinking that if we do that we should also change the description to indicate that this parameter should not be set if `Content` parameter is set - and same to the Content parameter.
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_PfxImport/DSC_PfxImport.psm1, line 1 at r3](https://reviewable.io/reviews/dsccommunity/certificatedsc/242#-MQVHLQxCOYU-x1oOVIV:-MR3nm2o1FZ-fp6YEZrQ:b-896fix) ([raw file](https://github.com/dsccommunity/certificatedsc/blob/ac421b611635530f4975fa4e7b69857de8b55e0b/source/DSCResources/DSC_PfxImport/DSC_PfxImport.psm1#L1)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Same comments for this file as the CertificateImport PSM1.
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_PfxImport/DSC_PfxImport.psm1, line 156 at r3](https://reviewable.io/reviews/dsccommunity/certificatedsc/242#-MQPpUbJ7VBVSjz8Ry4Z:-MR3nmv_BE-vJqhDmSvR:b-kb4357) ([raw file](https://github.com/dsccommunity/certificatedsc/blob/ac421b611635530f4975fa4e7b69857de8b55e0b/source/DSCResources/DSC_PfxImport/DSC_PfxImport.psm1#L156)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

:+1:
</blockquote></details>

Depending on export flag we would probably only get public key and due to encryption the output encoded value would not match and could not be used for comparison.   Thoughts?
___
*[source/DSCResources/DSC_PfxImport/DSC_PfxImport.psm1, line 386 at r3](https://reviewable.io/reviews/dsccommunity/certificatedsc/242#- [...]

2021-01-15 07:11 UTC, 39Delta reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/certificatedsc/242)* status: 1 of 16 files reviewed, 17 unresolved discussions (waiting on @39Delta, @PlagueHO, and @regedit32)

___
*[source/Examples/Resources/CertificateImport/3-CertificateImport_WithContent_Config.ps1, line 44 at r3](https://reviewable.io/reviews/dsccommunity/certificatedsc/242#-MQVHzlOEU4ejmSSziqA:-MR3sLC7BAQqEYvZGF3W:b-896fix) ([raw file](https://github.com/dsccommunity/certificatedsc/blob/ac421b611635530f4975fa4e7b69857de8b55e0b/source/Examples/Resources/CertificateImport/3-CertificateImport_WithContent_Config.ps1#L44)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

If we remove the required status on `Path` then we can remove it from the example
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-15 21:17 UTC, 39Delta reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/certificatedsc/242)* status: 1 of 16 files reviewed, 17 unresolved discussions (waiting on @39Delta, @PlagueHO, and @regedit32)

___
*[source/DSCResources/DSC_CertificateImport/DSC_CertificateImport.psm1, line 105 at r3](https://reviewable.io/reviews/dsccommunity/certificatedsc/242#-MQPoJNMDlPRfCQ3Xkpb:-MR6lzQN0WutexXh8MQP:bbwku0f) ([raw file](https://github.com/dsccommunity/certificatedsc/blob/ac421b611635530f4975fa4e7b69857de8b55e0b/source/DSCResources/DSC_CertificateImport/DSC_CertificateImport.psm1#L105)):*
<details><summary><i>Previously, 39Delta (switch21) wrote…</i></summary><blockquote>

We can for the public key but keep in mind the encoded value will be different if the user has configured a new friendly name through the parameter and should not be relied on for comparison.  The thumbprint is best ID to compare.  If we think their is value in exposing the currently installed cert value then I can add.  Thoughts?
</blockquote></details>

I am now returning the parameter value for Content in the Get-TargetResource function which should satisfy this comment.
___
*[source/DSCResources/DSC_PfxImport/DSC_PfxImport.psm1, line 156 at r3](https://reviewable.io/reviews/dsccommunity/certificatedsc/242#-MQPpUbJ7VBVSjz8Ry4Z:-MR6mFzb5ZoAOLdDQ9-t:bbwku0f) ([raw file](https://github.com/dsccommunity/certificatedsc/blob/ac421b611635530f4975fa4e7b69857de8b55e0b/source/DSCResources/DSC_PfxImport/DSC_PfxImport.psm1#L156)):*
<details><summary><i>Previously, 39Delta (switch21) wrote…</i></summary><blockquote>

Depending on export flag we would probably only get public key and due to encryption the output encoded value would not match and could not be used for comparison.   Thoughts?
</blockquote></details>

I am now returning the parameter value for Content in the Get-TargetResource function which should satisfy this comment.


<!-- Sent from Reviewable.io -->

2021-01-19 01:47 UTC, regedit32 reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/certificatedsc/242)* status: 1 of 16 files reviewed, 17 unresolved discussions (waiting on @39Delta, @PlagueHO, and @regedit32)

*[a discussion](https://reviewable.io/reviews/dsccommunity/certificatedsc/242#-MQPr1NbA6qa7bm0hfJj:-MRNJb1R5CzJoufTb7PT:b4c9lyr) (no related file):*
<details><summary><i>Previously, 39Delta (switch21) wrote…</i></summary><blockquote>

There were no changes to the Test-DscConfiguration logic as it only tests for the presence or absence of a certificate in the cert store by thumbprint.  The new parameters are ignored by this function.
</blockquote></details>

:thumbsup: 

---


<!-- Sent from Reviewable.io -->

2021-01-19 01:51 UTC, regedit32 reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/certificatedsc/242)* status: 1 of 16 files reviewed, 18 unresolved discussions (waiting on @39Delta, @PlagueHO, and @regedit32)

*[a discussion](https://reviewable.io/reviews/dsccommunity/certificatedsc/242#-MRNKeyE7oEStVvZGxoA:-MRNKeyFEkTbpm8aJvkY:bg7igkv) (no related file):*
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

---


<!-- Sent from Reviewable.io -->

2021-01-19 06:01 UTC, PlagueHO commented
Sorry about delay. Will finish review later in the week. Snowed under at work.

2021-01-22 17:05 UTC, 39Delta reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/certificatedsc/242)* status: 1 of 16 files reviewed, 18 unresolved discussions (waiting on @39Delta, @PlagueHO, and @regedit32)

___
*[tests/Integration/DSC_PfxImport.Integration.Tests.ps1, line 240 at r3](https://reviewable.io/reviews/dsccommunity/certificatedsc/242#-MQPqBc1E8Msd8clkCLN:-MRf2dv-6bMKh_cWUrtn:bj7g7cx) ([raw file](https://github.com/dsccommunity/certificatedsc/blob/ac421b611635530f4975fa4e7b69857de8b55e0b/tests/Integration/DSC_PfxImport.Integration.Tests.ps1#L240)):*
<details><summary><i>Previously, regedit32 (Reggie Gibson) wrote…</i></summary><blockquote>

> ```
>             It 'Should be able to call Get-DscConfiguration without throwing' {
>                 { Get-DscConfiguration -Verbose -ErrorAction Stop } | Should -Not -Throw
>             }
> ```
I'd recommend storing the output of Get-DscConfiguration and adding a test to assert the expected results.  This validates that each setting in the return hashtable is as expected.
</blockquote></details>

The return type and results are being tested in the unit tests.  Thoughts?


<!-- Sent from Reviewable.io -->

2021-01-22 17:06 UTC, 39Delta reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/certificatedsc/242)* status: 1 of 16 files reviewed, 18 unresolved discussions (waiting on @39Delta, @PlagueHO, and @regedit32)

___
*[tests/Integration/DSC_PfxImport.Integration.Tests.ps1, line 240 at r3](https://reviewable.io/reviews/dsccommunity/certificatedsc/242#-MQPqBc1E8Msd8clkCLN:-MRf2reO39sUdd47DVQH:b-896fix) ([raw file](https://github.com/dsccommunity/certificatedsc/blob/ac421b611635530f4975fa4e7b69857de8b55e0b/tests/Integration/DSC_PfxImport.Integration.Tests.ps1#L240)):*
<details><summary><i>Previously, 39Delta (switch21) wrote…</i></summary><blockquote>

The return type and results are being tested in the unit tests.  Thoughts?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-04 20:22 UTC, PlagueHO commented
/AzurePipelines run

2021-02-04 21:49 UTC, 39Delta commented
@PlagueHO The New-SelfSignedCertificateEx.zip that is downloaded by the common test helper module is corrupt and breaking the pipeline as it fails to extract.

2021-02-05 20:31 UTC, PlagueHO commented
Had no idea, but Script Center has been deprecated: https://docs.microsoft.com/en-us/teamblog/technet-gallery-retirement

I've created an issue to fix this and will submit the change now: https://github.com/dsccommunity/CertificateDsc/issues/250

I'm going to deprecate support for running these tests on Windows Server 2012R2 which "should" eliminate the need to use this script.

FYI, I'll be completing reviews this weekend. Apologies for the delays - have not had any capacity due to exams for day job.

2021-02-07 02:25 UTC, PlagueHO commented
I've submitted the fix for the CI: https://github.com/dsccommunity/CertificateDsc/pull/251 - Once that PR is through then you can rebase onto it and we'll get this merged.

2021-02-11 06:38 UTC, PlagueHO commented
Hi @39Delta  - can you resolve the conflicts on this and I'll finish the review. I've fixed the other issues now.

2021-02-11 07:17 UTC, 39Delta commented
@PlagueHO, Just merged in the latest changes and all is passing now.  Thanks for your help!

2021-02-12 21:08 UTC, PlagueHO requested changes
Thanks @39delta - looking awesome - just some really minor tweaks and then we'll merge.

> Reviewed 2 of 14 files at r1, 1 of 9 files at r2, 5 of 11 files at r4, 7 of 7 files at r6.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/certificatedsc/242#-:-MTN3h2Y3rj9CUYKIts6:bbcgu6i)* status: all files reviewed, 10 unresolved discussions (waiting on @39Delta and @regedit32)

___
*[source/DSCResources/DSC_CertificateImport/DSC_CertificateImport.psm1, line 179 at r6](https://reviewable.io/reviews/dsccommunity/certificatedsc/242#-MTN3_ZlDjTdViE5TLI1:-MTN3_Zm4-OcNA9GiYSa:bf6rvut) ([raw file](https://github.com/dsccommunity/certificatedsc/blob/0b81b2ea4f400463bd590348652bcd25540f8ddf/source/DSCResources/DSC_CertificateImport/DSC_CertificateImport.psm1#L179)):*
> ```PowerShell
>     )
> 
>     Write-Verbose -Message ( @(
> ```

Can you also add the `Assert-ResourceProperty @PSBoundParameter` to this function as well?
___
*[source/DSCResources/DSC_CertificateImport/DSC_CertificateImport.psm1, line 353 at r6](https://reviewable.io/reviews/dsccommunity/certificatedsc/242#-MTN3PI48Owv7FnfFPAp:-MTN3PI48Owv7FnfFPAq:b7py9ne) ([raw file](https://github.com/dsccommunity/certificatedsc/blob/0b81b2ea4f400463bd590348652bcd25540f8ddf/source/DSCResources/DSC_CertificateImport/DSC_CertificateImport.psm1#L353)):*
> ```PowerShell
>             -Store $Store
>     }
> }  # end function Test-TargetResource
> ```

I just noticed this is wrong - should be `Set-TargetResource` - sorry, must have been wrong for ages!
___
*[source/DSCResources/DSC_CertificateImport/DSC_CertificateImport.psm1, line 379 at r6](https://reviewable.io/reviews/dsccommunity/certificatedsc/242#-MTN0k5P9_OYV1W7yu3s:-MTN0k5P9_OYV1W7yu3t:b-r8i9ro) ([raw file](https://github.com/dsccommunity/certificatedsc/blob/0b81b2ea4f400463bd590348652bcd25540f8ddf/source/DSCResources/DSC_CertificateImport/DSC_CertificateImport.psm1#L379)):*
> ```PowerShell
>     if ($Ensure -ieq 'Present')
>     {
>         if ([string]::IsNullOrWhiteSpace($Content) -band [string]::IsNullOrWhiteSpace($Path))
> ```

Can you use [System.String] instead of [string] here?

Also,  can we check here if both are passed? If both values are passed we should also throw an exception.
___
*[source/DSCResources/DSC_PfxImport/DSC_PfxImport.psm1, line 386 at r3](https://reviewable.io/reviews/dsccommunity/certificatedsc/242#-MQVIYbj7zL10Sfgmpln:-MTN0Fcm47t4puquIl0O:b64zpf9) ([raw file](https://github.com/dsccommunity/certificatedsc/blob/ac421b611635530f4975fa4e7b69857de8b55e0b/source/DSCResources/DSC_PfxImport/DSC_PfxImport.psm1#L386)):*
<details><summary><i>Previously, 39Delta (switch21) wrote…</i></summary><blockquote>

I currently have it setup to force the use of Import-PfxCertificateEx when using the base64 content because the standard Import-PfxCertifcate command only support importing from a file.  WS2012R2 support should always support Import-PfxCertificateEx.  Thoughts?
</blockquote></details>

Right - good point. I'm wondering therefore at some point we go completely over to the *Ex functions. But for a later date.
___
*[source/DSCResources/DSC_PfxImport/DSC_PfxImport.psm1, line 469 at r6](https://reviewable.io/reviews/dsccommunity/certificatedsc/242#-MTN16zh5E7q4hOCjU8V:-MTN16zh5E7q4hOCjU8W:b-r8i9ro) ([raw file](https://github.com/dsccommunity/certificatedsc/blob/0b81b2ea4f400463bd590348652bcd25540f8ddf/source/DSCResources/DSC_PfxImport/DSC_PfxImport.psm1#L469)):*
> ```PowerShell
>     if ($Ensure -ieq 'Present')
>     {
>         if ([string]::IsNullOrWhiteSpace($Content) -band [string]::IsNullOrWhiteSpace($Path))
> ```

Can you use [System.String] instead of [string] here?

Also,  can we check here if both are passed? If both values are passed we should also throw an exception.
___
*[tests/Unit/CertificateDsc.Common.Tests.ps1, line 43 at r6](https://reviewable.io/reviews/dsccommunity/certificatedsc/242#-MTN1rtI7eZ98oAmsK-L:-MTN1rtJ-YDlEPKT8f54:b-augp85) ([raw file](https://github.com/dsccommunity/certificatedsc/blob/0b81b2ea4f400463bd590348652bcd25540f8ddf/tests/Unit/CertificateDsc.Common.Tests.ps1#L43)):*
> ```PowerShell
>     $validPath = "TestDrive:\$testFile"
> 
>     $tmpCertificateName = $(New-Guid).Guid + '.cer'
> ```

Are these variables used?
___
*[tests/Unit/DSC_CertificateImport.Tests.ps1, line 288 at r6](https://reviewable.io/reviews/dsccommunity/certificatedsc/242#-MTN2Kzm4DQiL4eAKmxh:-MTN2Kzn-bELQ-CmzJUA:b78svaq) ([raw file](https://github.com/dsccommunity/certificatedsc/blob/0b81b2ea4f400463bd590348652bcd25540f8ddf/tests/Unit/DSC_CertificateImport.Tests.ps1#L288)):*
> ```PowerShell
>             }
> 
>             Context 'When Content and Path parameters are null' {
> ```

We should also add a test for when both Content and Path parameters are set - which should be an invalid configuration.
___
*[tests/Unit/DSC_PfxImport.Tests.ps1, line 351 at r6](https://reviewable.io/reviews/dsccommunity/certificatedsc/242#-MTN2uT15uaCYE-y1TU1:-MTN2uT2A4Jv8ONEyJXH:b78svaq) ([raw file](https://github.com/dsccommunity/certificatedsc/blob/0b81b2ea4f400463bd590348652bcd25540f8ddf/tests/Unit/DSC_PfxImport.Tests.ps1#L351)):*
> ```PowerShell
>             }
> 
>             Context 'When Content and Path parameters are null' {
> ```

We should also add a test for when both Content and Path parameters are set - which should be an invalid configuration.


<!-- Sent from Reviewable.io -->

2021-02-15 06:02 UTC, 39Delta reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/certificatedsc/242)* status: 9 of 15 files reviewed, 10 unresolved discussions (waiting on @39Delta, @PlagueHO, and @regedit32)

___
*[source/DSCResources/DSC_CertificateImport/DSC_CertificateImport.psm1, line 179 at r6](https://reviewable.io/reviews/dsccommunity/certificatedsc/242#-MTN3_ZlDjTdViE5TLI1:-MTXLKx_46yME00k55_X:b32wtd) ([raw file](https://github.com/dsccommunity/certificatedsc/blob/0b81b2ea4f400463bd590348652bcd25540f8ddf/source/DSCResources/DSC_CertificateImport/DSC_CertificateImport.psm1#L179)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you also add the `Assert-ResourceProperty @PSBoundParameter` to this function as well?
</blockquote></details>

ok
___
*[source/DSCResources/DSC_CertificateImport/DSC_CertificateImport.psm1, line 353 at r6](https://reviewable.io/reviews/dsccommunity/certificatedsc/242#-MTN3PI48Owv7FnfFPAp:-MTXN21aB8NsXXGlIdcr:b-886gsx) ([raw file](https://github.com/dsccommunity/certificatedsc/blob/0b81b2ea4f400463bd590348652bcd25540f8ddf/source/DSCResources/DSC_CertificateImport/DSC_CertificateImport.psm1#L353)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

I just noticed this is wrong - should be `Set-TargetResource` - sorry, must have been wrong for ages!
</blockquote></details>

Fixed
___
*[source/DSCResources/DSC_CertificateImport/DSC_CertificateImport.psm1, line 379 at r6](https://reviewable.io/reviews/dsccommunity/certificatedsc/242#-MTN0k5P9_OYV1W7yu3s:-MTZGwl068ahtEjYclgA:b-qc7si5) ([raw file](https://github.com/dsccommunity/certificatedsc/blob/0b81b2ea4f400463bd590348652bcd25540f8ddf/source/DSCResources/DSC_CertificateImport/DSC_CertificateImport.psm1#L379)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you use [System.String] instead of [string] here?

Also,  can we check here if both are passed? If both values are passed we should also throw an exception.
</blockquote></details>

Type updated and tests now check if both parameters are used
___
*[source/DSCResources/DSC_PfxImport/DSC_PfxImport.psm1, line 469 at r6](https://reviewable.io/reviews/dsccommunity/certificatedsc/242#-MTN16zh5E7q4hOCjU8V:-MTZGceMAqgV-_bEi_Kf:bd9cnb1) ([raw file](https://github.com/dsccommunity/certificatedsc/blob/0b81b2ea4f400463bd590348652bcd25540f8ddf/source/DSCResources/DSC_PfxImport/DSC_PfxImport.psm1#L469)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you use [System.String] instead of [string] here?

Also,  can we check here if both are passed? If both values are passed we should also throw an exception.
</blockquote></details>

Updated type and tests to check for both.
___
*[tests/Unit/CertificateDsc.Common.Tests.ps1, line 43 at r6](https://reviewable.io/reviews/dsccommunity/certificatedsc/242#-MTN1rtI7eZ98oAmsK-L:-MTZGjuI6aqKSvVthpF8:bu49b7s) ([raw file](https://github.com/dsccommunity/certificatedsc/blob/0b81b2ea4f400463bd590348652bcd25540f8ddf/tests/Unit/CertificateDsc.Common.Tests.ps1#L43)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Are these variables used?
</blockquote></details>

No removed.
___
*[tests/Unit/DSC_CertificateImport.Tests.ps1, line 288 at r6](https://reviewable.io/reviews/dsccommunity/certificatedsc/242#-MTN2Kzm4DQiL4eAKmxh:-MTZGm3EBUANtpcD1Dge:bmdnojn) ([raw file](https://github.com/dsccommunity/certificatedsc/blob/0b81b2ea4f400463bd590348652bcd25540f8ddf/tests/Unit/DSC_CertificateImport.Tests.ps1#L288)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

We should also add a test for when both Content and Path parameters are set - which should be an invalid configuration.
</blockquote></details>

Test updated to check for both and added to test function
___
*[tests/Unit/DSC_PfxImport.Tests.ps1, line 351 at r6](https://reviewable.io/reviews/dsccommunity/certificatedsc/242#-MTN2uT15uaCYE-y1TU1:-MTZGsrY659rYMJ71nS6:bmdnojn) ([raw file](https://github.com/dsccommunity/certificatedsc/blob/0b81b2ea4f400463bd590348652bcd25540f8ddf/tests/Unit/DSC_PfxImport.Tests.ps1#L351)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

We should also add a test for when both Content and Path parameters are set - which should be an invalid configuration.
</blockquote></details>

Test updated to check for both and added to test function


<!-- Sent from Reviewable.io -->

2021-02-19 18:35 UTC, PlagueHO approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

Thank you so much for the massive effort in getting this through @39delta !

> Reviewed 11 of 11 files at r7.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/certificatedsc/242#-:-MTvZoRu4T_vZpA-ja_V:bdql104)* status: all files reviewed, 3 unresolved discussions (waiting on @39Delta and @regedit32)



<!-- Sent from Reviewable.io -->

2021-02-19 18:36 UTC, PlagueHO approved these changes
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/certificatedsc/242)* status: all files reviewed, 3 unresolved discussions (waiting on @39Delta and @regedit32)



<!-- Sent from Reviewable.io -->

2021-02-19 18:36 UTC, PlagueHO approved these changes
> Dismissed @regedit32 from a discussion.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/certificatedsc/242)* status: all files reviewed, 2 unresolved discussions (waiting on @39Delta)



<!-- Sent from Reviewable.io -->

2021-02-19 18:37 UTC, PlagueHO approved these changes
> Dismissed @regedit32 from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/certificatedsc/242)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-02-19 18:37 UTC, merged