BREAKING CHANGE: CertReq: Improve certificate match selectivity
dsccommunity/CertificateDsc pull request #271
Opened 2022-12-14 17:13 UTC by uw-dc

#### Pull Request (PR) description

*Breaking Change*: Support multiple certificates with the same `issuer` and `subject` by making `friendlyName` a mandatory (key) parameter

Prevent existing certificates with non-matching `friendlyName` and `template` being considered as existing desired certificates; This resolves problems where an incorrect existing certificate is compared with the desired state and `Test-TargetResource` consequentially returns `$false`.

#### This Pull Request (PR) fixes the following issues

- Fixes #121
- Fixes #269

- Replaces PR #206 

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [] Resource documentation added/updated in README.md.
- [] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

2022-12-14 17:22 UTC, uw-dc commented
An issue with ['GENERATE CONCEPTUAL HELP'](https://dev.azure.com/dsccommunity/CertificateDsc/_build/results?buildId=7151&view=logs&j=bce26a94-9049-50eb-6c1c-385ccbec51f9&t=512e4b73-7a3e-57af-0534-ae809c1351da&l=172); Looks environmental?

```
ERROR: Failed to import classes from file /home/vsts/work/1/s/source/DSCResources/DSC_CertificateExport/DSC_CertificateExport.schema.mof. Error Exception calling "ImportClasses" with "3" argument(s): "Unable to load shared library 'libmi' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibmi: cannot open shared object file: No such file or directory"
At /home/vsts/work/1/s/output/RequiredModules/DscResource.DocGenerator/0.11.1/DscResource.DocGenerator.psm1:1486 char:9
+         throw "Failed to import classes from file $FileName. Error $_ …
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

2022-12-15 14:03 UTC, uw-dc commented
@PlagueHO 

Is it possible please to get a review on this?
It would be really good for us to resolve the issues this PR covers as issue #121  is affecting our production hosts.

Thank you.

2022-12-15 20:34 UTC, PlagueHO requested changes
Hi @uw-dc - sorry about the delay. Looks great. Just some minor tweaks, nothing major.

> Reviewed 2 of 5 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/certificatedsc/271#-:-NJMUULY80fE9d4BcjGE:b9ehxzs)* status: all files reviewed, 6 unresolved discussions (waiting on @uw-dc)

___
*[`azure-pipelines.yml` line 27 at r3](https://reviewable.io/reviews/dsccommunity/certificatedsc/271#-NJMPhQG3l5dFWwQ9wJG:-NJMPhQH1aNAsKQsalbA:b-uqlhhe) ([raw file](https://github.com/dsccommunity/certificatedsc/blob/c68376f362af977062f5924d215d0fd286f1f9b3/azure-pipelines.yml#L27)):*
> ```YAML
>         displayName: 'Package Module'
>         pool:
>           vmImage: 'windows-latest'
> ```

We typically use ubuntu-latest for the package step. Not that it matters too much - but if there is a specific need then we should note it here (so I don't revert it later)
___
*[`CHANGELOG.md` line 8 at r3](https://reviewable.io/reviews/dsccommunity/certificatedsc/271#-NJMREFs8Jr-5i7FCoBh:-NJMREFs8Jr-5i7FCoBi:bca89gd) ([raw file](https://github.com/dsccommunity/certificatedsc/blob/c68376f362af977062f5924d215d0fd286f1f9b3/CHANGELOG.md#L8)):*
> ```Markdown
> ## [Unreleased]
> 
> - CertReq:
> ```

Can you move under the `### Changed` section`?
___
*[`CHANGELOG.md` line 9 at r3](https://reviewable.io/reviews/dsccommunity/certificatedsc/271#-NJMQuzy6HzvDvji_X-l:-NJMQuzz6-OldIlRbuJ0:b-xf4xn3) ([raw file](https://github.com/dsccommunity/certificatedsc/blob/c68376f362af977062f5924d215d0fd286f1f9b3/CHANGELOG.md#L9)):*
> ```Markdown
> 
> - CertReq:
>   - Made Certificate FriendlyName a mandatory parameter (key) so multiple certificates with same issuer and subject can be configured in the same DSC configuration - Fixes [Issue #269](https://github.com/dsccommunity/CertificateDsc/issues/269)
> ```

Can you reduce the line length to less than 100 chars on this line and the next one?
___
*[`CHANGELOG.md` line 9 at r3](https://reviewable.io/reviews/dsccommunity/certificatedsc/271#-NJMR8JyBs6gmsZYgPSe:-NJMR8JyBs6gmsZYgPSf:b-v74e5y) ([raw file](https://github.com/dsccommunity/certificatedsc/blob/c68376f362af977062f5924d215d0fd286f1f9b3/CHANGELOG.md#L9)):*
> ```Markdown
> 
> - CertReq:
>   - Made Certificate FriendlyName a mandatory parameter (key) so multiple certificates with same issuer and subject can be configured in the same DSC configuration - Fixes [Issue #269](https://github.com/dsccommunity/CertificateDsc/issues/269)
> ```

Can you include `BREAKING CHANGE: ` at the beginning of these lines? This will tell the pipeline to increase the major version number.
___
*[`source/DSCResources/DSC_CertReq/DSC_CertReq.psm1` line 202 at r3](https://reviewable.io/reviews/dsccommunity/certificatedsc/271#-NJMRZ7U8OiIWO3j11SO:-NJMRZ7U8OiIWO3j11SP:b3f23w5) ([raw file](https://github.com/dsccommunity/certificatedsc/blob/c68376f362af977062f5924d215d0fd286f1f9b3/source/DSCResources/DSC_CertReq/DSC_CertReq.psm1#L202)):*
> ```PowerShell
>     $cert = Get-ChildItem -Path Cert:\LocalMachine\My |
>         Where-Object -FilterScript {
>             (Compare-CertificateSubject -ReferenceSubject $_.Subject -DifferenceSubject $Subject) -and `
> ```

FYI: I like the improvement here - nice!
___
*[`source/DSCResources/DSC_CertReq/en-US/DSC_CertReq.strings.psd1` line 17 at r3](https://reviewable.io/reviews/dsccommunity/certificatedsc/271#-NJMRgSf97cudJEqPm8r:-NJMRgSf97cudJEqPm8s:bd5zukk) ([raw file](https://github.com/dsccommunity/certificatedsc/blob/c68376f362af977062f5924d215d0fd286f1f9b3/source/DSCResources/DSC_CertReq/en-US/DSC_CertReq.strings.psd1#L17)):*
> ```PowerShell
>     NoValidCertificateMessage = No valid certificate found with Subject '{0}', Issuer '{1}', FriendlyName '{2}' and CertificateTemplate '{3}'.
>     ExpiredCertificateMessage = The certificate found with Subject '{0}', Issuer '{1}', FriendlyName '{2}' and CertificateTemplate '{3}' has expired: {4}.
>     NoExistingSans = The certificate found with Subject '{0}', Issuer '{1}', FriendlyName '{2}' and CertificateTemplate '{3}' has no SANs, yet the following SANs are specified: {4}. Certificate has the Thumbprint '{5}'.
> ```

FYI: Consistency - Can you add `Message` to the end of the property name to differentiate it? Unless it is an error then add "Error" - not a major thing as we clearly haven't been 100% consistent here.
___
*[`tests/Unit/DSC_CertReq.Tests.ps1` line 1874 at r3](https://reviewable.io/reviews/dsccommunity/certificatedsc/271#-NJMU5wT4neQNGgF8RTu:-NJMU5wT4neQNGgF8RTv:b-pfu805) ([raw file](https://github.com/dsccommunity/certificatedsc/blob/c68376f362af977062f5924d215d0fd286f1f9b3/tests/Unit/DSC_CertReq.Tests.ps1#L1874)):*
> ```PowerShell
>                     -MockWith $mock_getCertificateTemplateName_validCertificateTemplate
> 
>                 # Mock -CommandName Get-CertificateSubjectAlternativeName `
> ```

Can you remove commented out lines here (and throughout)?
___
*[`tests/Unit/DSC_CertReq.Tests.ps1` line 1878 at r3](https://reviewable.io/reviews/dsccommunity/certificatedsc/271#-NJMTvyB0fNBKw6bWy54:-NJMTvyB0fNBKw6bWy55:br3si34) ([raw file](https://github.com/dsccommunity/certificatedsc/blob/c68376f362af977062f5924d215d0fd286f1f9b3/tests/Unit/DSC_CertReq.Tests.ps1#L1878)):*
> ```PowerShell
> 
>                 It 'Should return true' {
>                     Test-TargetResource @paramsStandard -Verbose | Should -Be $true
> ```

Can you change to `Should -BeTrue` (and `Should -BeFalse`) and throughout.


<!-- Sent from Reviewable.io -->

2022-12-18 20:34 UTC, PlagueHO commented
Sorry @uw-dc - will get onto this tonight.

2022-12-23 18:44 UTC, PlagueHO requested changes
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/certificatedsc/271)* status: all files reviewed, 2 unresolved discussions (waiting on @uw-dc)

___
*[`CHANGELOG.md` line 9 at r3](https://reviewable.io/reviews/dsccommunity/certificatedsc/271#-NJMQuzy6HzvDvji_X-l:-NK-Hjfi48Ol8l-zcgE1:bdlwrew) ([raw file](https://github.com/dsccommunity/certificatedsc/blob/c68376f362af977062f5924d215d0fd286f1f9b3/CHANGELOG.md#L9)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you reduce the line length to less than 100 chars on this line and the next one?
</blockquote></details>

Thank you! You can also wrap if you want. For example:
```powershell
 - Made Certificate FriendlyName a mandatory parameter (key) so multiple
   certificates with same issuer and subject can be configured in the same
   DSC configuration - Fixes [Issue #269](https://github.com/dsccommunity/CertificateDsc/issues/269)
```


<!-- Sent from Reviewable.io -->

2022-12-23 18:44 UTC, PlagueHO approved these changes
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/certificatedsc/271)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @uw-dc)



<!-- Sent from Reviewable.io -->

2022-12-23 18:45 UTC, PlagueHO approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

Thank you for contributing this! We'll leave it in prerelease for a few weeks and then once we'll push it out as a new major version.

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/certificatedsc/271#-:-NK-IGvo52ixTjXCloge:bi7p79o)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @uw-dc)



<!-- Sent from Reviewable.io -->

2022-12-23 18:45 UTC, merged